server:
    port: 18080
spring:
    datasource:
        url: jdbc:mysql://192.168.122.249:3306/data_dictionary??useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: mysql123
        driver-class-name: com.mysql.jdbc.Driver

